# Generated by Django 5.2.17 on 2026-09-28 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profil_agence'),
        ('clients', '0003_client_archivage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profil_en_ligne', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('AGENT', 'Agent de banque'), ('CLIENT', 'Client (espace en ligne)')], max_length=20),
        ),
        migrations.CreateModel(
            name='ActivationEspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('expire_le', models.DateTimeField()),
                ('tentatives', models.PositiveSmallIntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activation_espace', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activation_espace',
            },
        ),
    ]
