# Generated by Django 5.2.17 on 2026-09-23 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte', models.CharField(blank=True, max_length=24, unique=True)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('type_compte', models.CharField(choices=[('COURANT', 'Courant'), ('EPARGNE', 'Épargne')], max_length=20)),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('CLOTURE', 'Clôturé')], default='OUVERT', max_length=20)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comptes', to='clients.client')),
            ],
            options={
                'db_table': 'compte',
                'ordering': ['-date_ouverture'],
                'constraints': [models.CheckConstraint(condition=models.Q(('solde__gte', 0)), name='compte_solde_non_negatif')],
            },
        ),
    ]
