# Generated by Django 5.2.17 on 2026-09-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='motif_cloture',
            field=models.CharField(blank=True, choices=[('DEMANDE_CLIENT', 'Demande du client'), ('DECISION_BANQUE', 'Décision de la banque')], max_length=30),
        ),
    ]
