# Generated by Django 5.2.17 on 2026-09-23 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(blank=True, max_length=24, unique=True)),
                ('email_destinataire', models.EmailField(max_length=254)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('statut_envoi', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYEE', 'Envoyée'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('envoye_le', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='operations.transaction')),
            ],
            options={
                'db_table': 'facture',
                'ordering': ['-cree_le'],
            },
        ),
    ]
