# Generated by Django 5.2.17 on 2026-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('pays', models.CharField(db_index=True, max_length=80)),
                ('ville', models.CharField(db_index=True, max_length=80)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'banque',
                'ordering': ['nom'],
            },
        ),
    ]
