# Generated by Django 5.2.17 on 2026-09-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banques', '0002_agence'),
    ]

    operations = [
        migrations.AddField(
            model_name='banque',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
