# Generated by Django 5.2.17 on 2026-09-23 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('type_transaction', models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait'), ('VIREMENT', 'Virement')], max_length=20)),
                ('sens', models.CharField(choices=[('CREDIT', 'Crédit'), ('DEBIT', 'Débit')], max_length=10)),
                ('reference_virement', models.UUIDField(blank=True, db_index=True, null=True)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='comptes.compte')),
                ('compte_contrepartie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_contrepartie', to='comptes.compte')),
            ],
            options={
                'db_table': 'transaction',
                'ordering': ['-date_transaction'],
                'constraints': [models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='transaction_montant_positif')],
            },
        ),
    ]
