# Generated by Django 5.2.17 on 2026-09-23 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('prenom', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('numero_client', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='banques.banque')),
            ],
            options={
                'db_table': 'client',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
